name: nosdart
description: CLI-based Nostr client written in Dart
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  bech32: ^0.2.2
  convert: ^3.1.2
  crypto: ^3.0.6
  nostr: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
